owner: TheBobPony
repo: bpstatus

sites:
  - name: Downloads
    url: https://dl.bobpony.com
status-website:
  cname: status.bobpony.com
  logoUrl: https://bobpony.com/img/favicon.png
  name: Status
  introTitle: BobPony.com status
  introMessage: Monitor the status of its services here.
  navbar:
    - title: Home
      href: https://bobpony.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
